package S13Swing.secondTry.formularios;

import S13Swing.secondTry.clases.Aeropuerto;
import S13Swing.secondTry.clases.AeropuertoPrivado;
import S13Swing.secondTry.clases.AeropuertoPublico;
import S13Swing.secondTry.utilidades.MetodosSueltos;
import S13Swing.secondTry.utilidades.VariablesGlobales;

import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    private DefaultTableModel modeloTabla;

    private final int PRIVADO = 1;
    private final int PUBLICO = 2;

    /*
        En la ventana Principal, añade un JTextfield encima de la tabla de
        aeropuertos y cuando se escriba una letra filtre por coincidencia en el nombre.
        Usa el evento de teclado para ello.
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        MetodosSueltos.leerAeropuertos(); // Relleno los aeropuertos del fichero en la lista

        this.buttonGroup1.add(this.rdbPrivado);
        this.buttonGroup1.add(this.rdbPublico);

        this.cargarDatos(PRIVADO, "");
    }

    public void cargarDatos(int tipo, String coincidenciaNombre) {

        this.modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tblAeropuertos.setModel(modeloTabla);

        int numColumnas = 0;

        modeloTabla.addColumn("Id");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Pais");
        modeloTabla.addColumn("Numero");
        modeloTabla.addColumn("Calle");
        modeloTabla.addColumn("Ciudad");
        modeloTabla.addColumn("Año");
        modeloTabla.addColumn("Capacidad");

        if (tipo == PRIVADO) {
            modeloTabla.addColumn("Socios");
            numColumnas = 9;
        } else {
            modeloTabla.addColumn("Financiacion");
            modeloTabla.addColumn("Discapacitados");
            numColumnas = 10;
        }

        this.tblAeropuertos.getColumnModel().getColumn(0).setPreferredWidth(20);

        Object[] fila;

        for (Aeropuerto aux : VariablesGlobales.aeropuertos) {

            if (aux.getNombre().toLowerCase().contains(coincidenciaNombre.toLowerCase())) {
                fila = new Object[numColumnas];

                fila[0] = aux.getId();
                fila[1] = aux.getNombre();
                fila[2] = aux.getDireccion().getPais();
                fila[3] = aux.getDireccion().getNumero();
                fila[4] = aux.getDireccion().getCalle();
                fila[5] = aux.getDireccion().getCiudad();
                fila[6] = aux.getAnioInauguracion();
                fila[7] = aux.getCapacidad();

                if (tipo == PRIVADO && aux instanceof AeropuertoPrivado) {
                    AeropuertoPrivado ap = (AeropuertoPrivado) aux;
                    fila[8] = ap.getNumSocios();
                    modeloTabla.addRow(fila);

                } else if (tipo == PUBLICO && aux instanceof AeropuertoPublico) {
                    AeropuertoPublico ap = (AeropuertoPublico) aux;
                    fila[8] = ap.getFinanciacion();
                    fila[9] = ap.getNumTrabajadoresDiscapacitados();
                    modeloTabla.addRow(fila);

                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAeropuertos = new javax.swing.JTable();
        rdbPrivado = new javax.swing.JRadioButton();
        rdbPublico = new javax.swing.JRadioButton();
        txtFiltroNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAeropuertos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(tblAeropuertos);

        rdbPrivado.setSelected(true);
        rdbPrivado.setText("Privado");
        rdbPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPrivadoActionPerformed(evt);
            }
        });

        rdbPublico.setText("Público");
        rdbPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPublicoActionPerformed(evt);
            }
        });

        txtFiltroNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroNombreKeyReleased(evt);
            }
        });

        jLabel1.setText("Escribe un nombre");

        jMenu3.setText("Aeropuertos");

        jMenuItem1.setText("Añadir...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Editar...");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Borrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Ganancias");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Mostrar información");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Aviones");

        jMenuItem6.setText("Añadir...");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Activar/Desactivar");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Borrar...");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdbPrivado)
                                                .addGap(27, 27, 27)
                                                .addComponent(rdbPublico)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdbPrivado)
                                        .addComponent(rdbPublico)
                                        .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        AniadirAeropuerto ventana = new AniadirAeropuerto(this, true);
        ventana.setVisible(true);
        if (this.rdbPrivado.isSelected()) {
            this.cargarDatos(PRIVADO, this.txtFiltroNombre.getText());
        } else {
            this.cargarDatos(PUBLICO, this.txtFiltroNombre.getText());
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rdbPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPrivadoActionPerformed
        this.cargarDatos(PRIVADO, this.txtFiltroNombre.getText());
    }//GEN-LAST:event_rdbPrivadoActionPerformed

    private void rdbPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPublicoActionPerformed
        this.cargarDatos(PUBLICO, this.txtFiltroNombre.getText());
    }//GEN-LAST:event_rdbPublicoActionPerformed

    private void txtFiltroNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroNombreKeyPressed

    }//GEN-LAST:event_txtFiltroNombreKeyPressed

    private void txtFiltroNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroNombreKeyReleased
        if (this.rdbPrivado.isSelected()) {
            this.cargarDatos(PRIVADO, this.txtFiltroNombre.getText());
        } else {
            this.cargarDatos(PUBLICO, this.txtFiltroNombre.getText());
        }
    }//GEN-LAST:event_txtFiltroNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbPrivado;
    private javax.swing.JRadioButton rdbPublico;
    private javax.swing.JTable tblAeropuertos;
    private javax.swing.JTextField txtFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
